#!/usr/bin/python

import serial
import pynmea2
import rospy
from sensor_msgs.msg import NavSatFix

serial_port = serial.Serial("/dev/ttyAMA0", 9600, timeout=0.5)

def decimal_degrees(d_m):
    """Convert the degrees & minutes number from the GPS to decimal degrees
    
    We get the degrees and minutes unseparated, i.e. (100*degrees)+minutes
    """
    d_m = float(d_m)
    degrees = d_m // 100
    minutes = d_m % 100
    return degrees + (minutes / 60)

def pos_publisher():
    while not rospy.is_shutdown():
        gps_data = serial_port.readline()
        if 'GGA' in gps_data:
            fix = pynmea2.parse(gps_data)
            msg = NavSatFix()
            if fix.lat == '':
                continue
            msg.latitude = decimal_degrees(fix.lat)
            msg.longitude = decimal_degrees(fix.lon)
            pos_pub.publish(msg)

if __name__ == '__main__':
    try:
        pos_pub = rospy.Publisher('/position', NavSatFix, queue_size=10)
        rospy.init_node("publish_gps_position", anonymous=True)
        pos_publisher()
    except rospy.ROSInterruptException:
        pass
