#!/usr/bin/python
from __future__ import print_function

import os
import serial
import subprocess
import re
import sys

import pynmea2

date = raw_input("Date [YYYY-MM-DD]> ").strip()
if not re.match("\d{4}-\d{2}-\d{2}", date):
    sys.exit("Date didn't match required format")

def get_gps_time(serial_port):
    streamreader = pynmea2.NMEAStreamReader()
    while True:
        line = serial_port.readline()
        if not line.strip():
            continue
        print(repr(line))

        try:
            batch = streamreader.next(line)
        except (pynmea2.ParseError, pynmea2.ChecksumError, UnicodeError):
            s = "Error parsing GPS data.\nbuffer={!r}\nline={!r}\n{}\n".format(
                        streamreader.buffer, line, traceback.format_exc()
            )
            print(s)
            print("Trying again...")
            streamreader.stream = b''
            continue

        for msg in batch:
            if (msg.sentence_type == 'GGA') and (msg.timestamp is not None):
                return msg.timestamp

serial_port = serial.Serial("/dev/ttyAMA0", 9600, timeout=0.5)
print("Getting time from GPS...")
from datetime import time
time = get_gps_time(serial_port)

dts = date + 'T' + time.strftime('%H:%M:%S')
print("Setting clock to:", dts)
print("  (may require sudo password)")
subprocess.check_call(["sudo", "date", "+%Y-%m-%dT%H:%M:%S", "-s", dts])
print("Done")
