#!/bin/sh 

# This script was created from http://www.pyimagesearch.com/2015/10/26/how-to-install-opencv-3-on-raspbian-jessie/

cd ~

# Update and upgrade existing packages
sudo apt-get --assume-yes update
sudo apt-get --assume-yes upgrade

# Install a few developer tools
sudo apt-get install --assume-yes build-essential git cmake pkg-config

# Install image I/O packages which allow us to load image file formats such as JPEG, PNG, TIFF, etc.
sudo apt-get install --assume-yes libjpeg-dev libtiff5-dev libjasper-dev libpng12-dev

# Install video I/O packages which allow us to load various video file formats as well as work with video streams
sudo apt-get install --assume-yes libavcodec-dev libavformat-dev libswscale-dev libv4l-dev
sudo apt-get install --assume-yes libxvidcore-dev libx264-dev

# Install the GTK development library so we can compile the highgui  sub-module of OpenCV, 
# which allows us to display images to our screen and build simple GUI interfaces
sudo apt-get install --assume-yes libgtk2.0-dev

# Install added dependencies to optimize opencv
sudo apt-get install --assume-yes libatlas-base-dev gfortran

# Install python 2.7 header files
sudo apt-get install --assume-yes python2.7-dev

# Grab OpenCV from repository
cd ~
wget -O opencv.zip https://github.com/Itseez/opencv/archive/3.0.0.zip
unzip opencv.zip

wget -O opencv_contrib.zip https://github.com/Itseez/opencv_contrib/archive/3.0.0.zip
unzip opencv_contrib.zip

# Compile and install OpenCV
cd ~/opencv-3.0.0/
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib-3.0.0/modules -D BUILD_EXAMPLES=ON ..
make -j4
sudo make install
sudo ldconfig
