FROM jamak9/sailing-robot:indigo-desktop-catkin
Maintainer Martin Biggs

USER root
RUN apt-get --assume-yes install libgeos-dev python-scipy python-pip \
    && pip install Latlon shapely pynmea2 spidev wiringpi2 tornado

USER pi
RUN bash -c "echo 'source /home/pi/sailing-robot/devel/setup.bash' >> ~/.bashrc"
RUN bash -c "echo 'cd ~' >> ~/.bashrc"
RUN bash -c "echo 'sudo service ssh start' > ~/start_ssh_server"
RUN bash -c "chmod u+x ~/start_ssh_server"
