#!/usr/bin/python
#
# Node publishes apparent wind direction
# DUMMY NODE, at the moment it just keeps publishing a constant wind direction
# as specified in the parameters file

import rospy
from sensor_msgs.msg import NavSatFix

dummy_wp = rospy.get_param("/dummy")

def wp_publisher():
    msg = NavSatFix()
    msg.latitude = dummy_wp['latitude']
    msg.longitude = dummy_wp['longitude']
    rate = rospy.Rate(rospy.get_param("/config/rate"))

    while not rospy.is_shutdown():
        wp_pub.publish(msg)
        rate.sleep()


if __name__ == '__main__':
    try:
        wp_pub = rospy.Publisher('/next_wp', NavSatFix, queue_size=10)
        rospy.init_node("publish_dummy_waypoint", anonymous=True)
        wp_publisher()
    except rospy.ROSInterruptException:
        pass
