#!/usr/bin/env python3
"""Control the sail servo

Subscribes: sailsheet_normalized (Float32)
"""
import time
import rclpy
from rclpy.node import Node
from std_msgs.msg import Float32

try:
    import pigpio
    PIGPIO_AVAILABLE = True
except ImportError:
    PIGPIO_AVAILABLE = False


class ActuatorDriverSail(Node):
    def __init__(self):
        super().__init__('actuator_driver_sail')

        self.declare_parameter('sail.pin', 24)
        self.declare_parameter('sail.servolowerlimits', 1000.0)
        self.declare_parameter('sail.servohigherlimits', 2000.0)
        self.declare_parameter('do_post', False)

        self.sail_gpio = self.get_parameter('sail.pin').value
        self.min_pwm = self.get_parameter('sail.servolowerlimits').value
        self.max_pwm = self.get_parameter('sail.servohigherlimits').value
        do_post = self.get_parameter('do_post').value

        self.debug_pub = self.create_publisher(Float32, 'debug_sailsheet_pwm', 10)

        if PIGPIO_AVAILABLE:
            self.pi_pwm = pigpio.pi()
            self.pi_pwm.set_mode(self.sail_gpio, pigpio.OUTPUT)
            if do_post:
                self.post()
        else:
            self.pi_pwm = None
            self.get_logger().warn('pigpio not available - running in simulation mode')

        self.create_subscription(Float32, 'sailsheet_normalized', self.sail_servo_update, 10)

    def sail_servo_update(self, msg):
        sheet_normalized = msg.data
        sheet_pwm = (sheet_normalized * (self.max_pwm - self.min_pwm)) + self.min_pwm
        pwm_msg = Float32()
        pwm_msg.data = float(sheet_pwm)
        self.debug_pub.publish(pwm_msg)
        if self.pi_pwm:
            self.pi_pwm.set_servo_pulsewidth(self.sail_gpio, sheet_pwm)

    def post(self):
        self.get_logger().warn('sail test: sheet in')
        self.pi_pwm.set_servo_pulsewidth(self.sail_gpio, self.min_pwm)
        time.sleep(3)
        self.get_logger().warn('sail test: sheet out')
        self.pi_pwm.set_servo_pulsewidth(self.sail_gpio, self.max_pwm)
        time.sleep(3)


def main(args=None):
    rclpy.init(args=args)
    node = ActuatorDriverSail()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
