#!/usr/bin/env python3
"""Control the rudder servo

Subscribes: rudder_control (Int16)
"""
import time
import rclpy
from rclpy.node import Node
from std_msgs.msg import Int16

try:
    import pigpio
    PIGPIO_AVAILABLE = True
except ImportError:
    PIGPIO_AVAILABLE = False


class ActuatorDriverRudder(Node):
    def __init__(self):
        super().__init__('actuator_driver_rudder')

        self.declare_parameter('rudder.PWMoffset', 0.0)
        self.declare_parameter('rudder.servolowerlimits', 1000.0)
        self.declare_parameter('rudder.servohigherlimits', 2000.0)
        self.declare_parameter('rudder.maxAngle', 40.0)
        self.declare_parameter('rudder.pin', 13)
        self.declare_parameter('do_post', False)

        self.pwm_offset = self.get_parameter('rudder.PWMoffset').value
        self.lower_limits = self.get_parameter('rudder.servolowerlimits').value
        self.higher_limits = self.get_parameter('rudder.servohigherlimits').value
        self.neutral = (self.lower_limits + self.higher_limits) / 2
        self.range = self.higher_limits - self.lower_limits
        self.pin = self.get_parameter('rudder.pin').value
        do_post = self.get_parameter('do_post').value

        if PIGPIO_AVAILABLE:
            self.pi = pigpio.pi()
            self.pi.set_mode(self.pin, pigpio.OUTPUT)
            if do_post:
                self.post()
        else:
            self.pi = None
            self.get_logger().warn('pigpio not available - running in simulation mode')

        self.create_subscription(Int16, 'rudder_control', self.rudder_servo_pwm_control, 10)

    def rudder_servo_pwm_control(self, data):
        degrees = data.data
        pwm = self.range * (-1.0 * degrees) / 90 + self.neutral + self.pwm_offset
        if self.pi:
            self.pi.set_servo_pulsewidth(self.pin, pwm)

    def post(self):
        self.get_logger().warn('rudder test: lower limit')
        for _ in range(4):
            self.pi.set_servo_pulsewidth(self.pin, self.neutral)
            time.sleep(0.25)
            self.pi.set_servo_pulsewidth(self.pin, self.lower_limits)
            time.sleep(0.25)

        self.get_logger().warn('rudder test: higher limit')
        for _ in range(4):
            self.pi.set_servo_pulsewidth(self.pin, self.neutral)
            time.sleep(0.25)
            self.pi.set_servo_pulsewidth(self.pin, self.higher_limits)
            time.sleep(0.25)


def main(args=None):
    rclpy.init(args=args)
    node = ActuatorDriverRudder()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
