#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from std_msgs.msg import Float32, Int16, String

from sailing_robot.pid_data import PID_Data
import sailing_robot.pid_control as _PID
from sailing_robot.navigation import angle_subtract


class ActuatorDemandRudder(Node):
    def __init__(self):
        super().__init__('actuator_demand_rudder')
        self.data = PID_Data()

        self.declare_parameter('rudder.control.Kp', 0.5)
        self.declare_parameter('rudder.control.Ki', 0.0)
        self.declare_parameter('rudder.control.Kd', 0.0)
        self.declare_parameter('rudder.maxAngle', 40.0)
        self.declare_parameter('config.rate', 10)

        kp = self.get_parameter('rudder.control.Kp').value
        ki = self.get_parameter('rudder.control.Ki').value
        kd = self.get_parameter('rudder.control.Kd').value
        self.max_angle = self.get_parameter('rudder.maxAngle').value
        rate_hz = self.get_parameter('config.rate').value

        self.controller = _PID.PID(kp, ki, kd, self.max_angle, -self.max_angle)

        self.pub = self.create_publisher(Int16, 'rudder_control', 10)
        self.create_subscription(Float32, 'goal_heading', self.data.update_goal_heading, 10)
        self.create_subscription(Float32, 'heading', self.data.update_heading, 10)
        self.create_subscription(String, 'sailing_state', self.data.update_sailing_state, 10)
        self.create_subscription(Float32, 'tack_rudder', self.data.update_tack_rudder, 10)

        self.timer = self.create_timer(1.0 / rate_hz, self.publish_rudder)

    def publish_rudder(self):
        self.get_logger().debug('Sailing state: %s' % self.data.sailing_state)
        if self.data.sailing_state == 'normal':
            rawangle = -self.controller.update_PID(angle_subtract(
                self.data.heading, self.data.goal_heading))
            angle = _PID.saturation(rawangle, -self.max_angle, self.max_angle)
            self.get_logger().debug('Angle: %s' % angle)
        else:
            rawangle = self.data.tack_rudder
            angle = _PID.saturation(rawangle, -self.max_angle, self.max_angle)

        msg = Int16()
        msg.data = int(angle)
        self.pub.publish(msg)


def main(args=None):
    rclpy.init(args=args)
    node = ActuatorDemandRudder()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
