#!/usr/bin/env python3
"""Dump all parameters, to match up with our rosbag files."""
from datetime import datetime
import json
import os.path

import rclpy
from rclpy.node import Node

FILENAME_BASE = '~/sailing-robot/params-dump_{}_{}.json'


class DebuggingDumpParams(Node):
    def __init__(self):
        super().__init__('debugging_dump_params')

        self.declare_parameter('log_name', '')
        log_name = self.get_parameter('log_name').value

        filename = FILENAME_BASE.format(
            log_name, datetime.now().strftime('%Y-%m-%dT%H.%M.%S'))
        filename = os.path.expanduser(filename)

        params = {
            name: self.get_parameter(name).value
            for name in self._parameters
        }

        with open(filename, 'w') as f:
            json.dump(params, f, indent=2, default=str)

        self.get_logger().info('Parameters dumped to %s' % filename)


def main(args=None):
    rclpy.init(args=args)
    node = DebuggingDumpParams()
    try:
        rclpy.spin_once(node, timeout_sec=1.0)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
