#!/usr/bin/env python3
"""Supply browser view of ros topics in local network."""

import json
import os
import rclpy
from rclpy.node import Node
from std_msgs.msg import Float32, Float64, Int16, String, Bool
from sensor_msgs.msg import NavSatFix

try:
    import tornado.ioloop
    import tornado.web
    import tornado.websocket
    TORNADO_AVAILABLE = True
except ImportError:
    TORNADO_AVAILABLE = False

PORT = 8448
STATIC_PATH = os.path.expanduser('~/sailing-robot/dashboard/src')

SIMPLE_TOPICS = [
    ('heading', Float32),
    ('goal_heading', Float32),
    ('rudder_control', Int16),
    ('sailing_state', String),
    ('dbg_helming_procedure', String),
    ('wind_direction_apparent', Float64),
    ('dbg_distance_to_waypoint', Float32),
    ('dbg_heading_to_waypoint', Float32),
    ('gps_satellites', Int16),
    ('task_ix', Int16),
    ('active_task_kind', String),
    ('wind_direction_average', Float32),
    ('camera_detection', String),
]


class DebuggingDashboard(Node):
    def __init__(self):
        super().__init__('debugging_dashboard')

        self.data = {}
        for topic, msg_type in SIMPLE_TOPICS:
            self.data[topic] = None
            self.create_subscription(
                msg_type, topic,
                lambda msg, t=topic: self._update(t, msg),
                10
            )

        self.create_subscription(NavSatFix, 'position', self._update_position, 10)

        if TORNADO_AVAILABLE:
            self.get_logger().info('Dashboard available at http://localhost:%d' % PORT)
            self._start_server()
        else:
            self.get_logger().warn('tornado not available - dashboard disabled')

    def _update(self, topic, msg):
        self.data[topic] = msg.data

    def _update_position(self, msg):
        self.data['position'] = {'lat': msg.latitude, 'lon': msg.longitude}

    def _start_server(self):
        dashboard_data = self.data

        class DataHandler(tornado.websocket.WebSocketHandler):
            def open(self):
                self.write_message(json.dumps(dashboard_data, default=str))

            def on_message(self, message):
                pass

        class IndexHandler(tornado.web.RequestHandler):
            def get(self):
                self.write('Sailing Robot Dashboard')

        app = tornado.web.Application([
            (r'/', IndexHandler),
            (r'/ws', DataHandler),
            (r'/static/(.*)', tornado.web.StaticFileHandler, {'path': STATIC_PATH}),
        ])
        app.listen(PORT)


def main(args=None):
    rclpy.init(args=args)
    node = DebuggingDashboard()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
