#!/usr/bin/env python3
# Log GPS data in the CSV format required by the rules

import csv
from datetime import datetime
import os.path
import rclpy
from rclpy.node import Node
from sailing_robot.msg import gpswtime

RECORDS_DIR = os.path.expanduser('~/sailing-robot')


class DebuggingGpsLog(Node):
    def __init__(self):
        super().__init__('debugging_gps_log')

        self.declare_parameter('log_name', '')
        log_name = self.get_parameter('log_name').value

        filename = 'gps-trace_{}_{}.csv'.format(
            log_name, datetime.now().strftime('%Y-%m-%dT%H.%M.%S'))
        self.day_of_month = datetime.now().day

        os.makedirs(RECORDS_DIR, exist_ok=True)
        self.csv_file = open(os.path.join(RECORDS_DIR, filename), 'w', newline='')
        self.csvw = csv.writer(self.csv_file)

        self.create_subscription(gpswtime, 'gps_fix', self.write_record, 10)
        self.get_logger().info(f'GPS logging to {filename}')

    def write_record(self, msg):
        ts = '%02d%02d%02d%02d' % (msg.time_h, msg.time_m, msg.time_s, self.day_of_month)
        lat = int(msg.fix.latitude * 1e7)
        lon = int(msg.fix.longitude * 1e7)
        self.csvw.writerow([ts, lat, lon])

    def destroy_node(self):
        self.csv_file.close()
        super().destroy_node()


def main(args=None):
    rclpy.init(args=args)
    node = DebuggingGpsLog()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
