#!/usr/bin/python
# This file is a draft for the futur helming/procedure system, nomenclature and variable/class names are likely to change

# TODO
# import stuff


class Helming():
    def __init__(self):
        # subscribe to sailing state

        self.rate = rospy.Rate(rospy.get_param("config/rate"))
        ProcedureList = [tack, jibe, ..]
        self.currentProcedureId = 0

        self.currentProcedure = None
        self.Runner()


    def Runner(self):
        while not rospy.is_shutdown():

            if self.sailing_state == 'normal':
                if self.currentProcedure:
                    self.currentProcedure.end()
                    self.currentProcedure = None
                set_rudder.PID()
                set_sail.wind()
            else:
                self.run_procedure()
            
            self.rate.sleep()


    def run_procedure(self):
        
        if not self.currentProcedure:
            # no procedure have been started
            self.currentProcedureId = 0
            self.currentProcedure = ProcedureList[self.currentProcedureId](self.sailing_state)

        elif self.currentProcedure.check_timeout():
            # if time out we start the next procedure in the list
            self.currentProcedureId = (self.currentProcedureId + 1) % len(self.ProcedureList)
            self.currentProcedure = ProcedureList[self.currentProcedureId](self.sailing_state)

        # we advance to the next timestep 
        self.currentProcedure.loop()



########################################################################






class ProcedureBase():
    def __Init__(self):
        self.start_time = ...
        # TODO: subscribe to stuff 

    def is_failed(self):
        """
        Am I out of time?
        Am I failing?
        """
        return currenttime - self.start_time > self.timeout

    def end(self):


class TackProcedure(ProcedureBase):
    """
        Basic Tack procedure
    """
    def __Init__(self, sailing_state, timeout=15):
        super().__Init__(self)
        self.sailing_state = sailing_state

    def loop(self):
        set_sail.wind()
        if self.sailing_state == "switch_to_port_tack":
            set_rudder.min()
        else:
            set_rudder.max()



class JibeProcedure(ProcedureBase):
    """
        Basic Jibe procedure
    """
    def __Init__(self, sailing_state, timeout=15):
        super().__Init__(self)
        self.sailing_state = sailing_state

    def loop(self):
        set_sail.wind()
        if self.sailing_state == "switch_to_port_tack":
            set_rudder.max()
        else:
            set_rudder.min()


