#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from std_msgs.msg import Float32


class DummyHeading(Node):
    def __init__(self):
        super().__init__('publish_dummy_heading_data')

        self.declare_parameter('dummy.heading', 0.0)
        self.declare_parameter('config.rate', 10)

        self.heading = self.get_parameter('dummy.heading').value
        rate_hz = self.get_parameter('config.rate').value

        self.heading_pub = self.create_publisher(Float32, 'heading', 10)
        self.timer = self.create_timer(1.0 / rate_hz, self.publish_heading)

    def publish_heading(self):
        msg = Float32()
        msg.data = float(self.heading)
        self.heading_pub.publish(msg)


def main(args=None):
    rclpy.init(args=args)
    node = DummyHeading()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
