#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from std_msgs.msg import Float64


class DummyApparentWindDirection(Node):
    def __init__(self):
        super().__init__('publish_dummy_wind_data')

        self.declare_parameter('dummy.wind_direction_apparent', 180.0)
        self.declare_parameter('config.rate', 10)

        self.wind_direction = self.get_parameter('dummy.wind_direction_apparent').value
        rate_hz = self.get_parameter('config.rate').value

        self.wind_pub = self.create_publisher(Float64, 'wind_direction_apparent', 10)
        self.timer = self.create_timer(1.0 / rate_hz, self.publish_wind)

    def publish_wind(self):
        msg = Float64()
        msg.data = float(self.wind_direction)
        self.wind_pub.publish(msg)


def main(args=None):
    rclpy.init(args=args)
    node = DummyApparentWindDirection()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
