#!/usr/bin/env python3

from datetime import datetime
import rclpy
from rclpy.node import Node
from sensor_msgs.msg import NavSatFix
from sailing_robot.msg import gpswtime


class DummyPosition(Node):
    def __init__(self):
        super().__init__('publish_dummy_position_data')

        self.declare_parameter('dummy.latitude', 50.8)
        self.declare_parameter('dummy.longitude', 1.0)
        self.declare_parameter('config.rate', 10)

        self.latitude = self.get_parameter('dummy.latitude').value
        self.longitude = self.get_parameter('dummy.longitude').value
        rate_hz = self.get_parameter('config.rate').value

        self.position_pub = self.create_publisher(NavSatFix, 'position', 10)
        self.gps_pub = self.create_publisher(gpswtime, 'gps_fix', 10)

        self.timer = self.create_timer(1.0 / rate_hz, self.publish_position)

    def publish_position(self):
        position = NavSatFix()
        position.latitude = float(self.latitude)
        position.longitude = float(self.longitude)
        self.position_pub.publish(position)

        now = datetime.utcnow()
        wtime = gpswtime()
        wtime.fix = position
        wtime.time_h = now.hour
        wtime.time_m = now.minute
        wtime.time_s = now.second
        self.gps_pub.publish(wtime)


def main(args=None):
    rclpy.init(args=args)
    node = DummyPosition()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
