#!/usr/bin/python
# READY FOR MIT
# STILL A WORK IN PROGRESS, DO NOT USE

import rospy
from std_msgs.msg import Float32, Float64, String

import time, math


class Force_jibe():
    def __init__(self):
        """
        """
        self.jibe_tack_now_pub = rospy.Publisher('jibe_tack_now', String, queue_size=10)

        rospy.init_node("Force_jibe", anonymous=True)

        rospy.Subscriber('sailing_state', String, self.update_sailing_state)
        self.sailing_state = 'normal'
        self.previous_sailing_state = 'normal'
        self.timer = time.time()


        self.rate = rospy.Rate(rospy.get_param("config/rate"))
        
        self.time_tack = rospy.get_param("force_jibe/time_tack")
#         self.distance_new_wp = rospy.get_param("force_jibe/distance_new_wp")

        self.looper()

    def update_sailing_state(self, msg):
        self.sailing_state = msg.data
        if msg.data == 'normal' or \
                self.previous_sailing_state != self.sailing_state:
            self.timer = time.time()
        self.previous_sailing_state = self.sailing_state 

    def looper(self):

        while not rospy.is_shutdown():
           
            # check tacking issue
            if self.sailing_state != 'normal' and \
                    (time.time() - self.timer) > self.time_tack:
                self.timer = time.time()
                rospy.logerr("Issue with tacking/jibing")
                self.jibe_tack_now_pub.publish('auto')


            self.rate.sleep()


if __name__ == '__main__':
    try:
        Force_jibe()
    except rospy.ROSInterruptException:
        pass

