#!/usr/bin/env python3

import time
import rclpy
from rclpy.node import Node
from std_msgs.msg import String


class ForceJibe(Node):
    def __init__(self):
        super().__init__('Force_jibe')

        self.declare_parameter('config.rate', 10)
        self.declare_parameter('force_jibe.time_tack', 30.0)

        rate_hz = self.get_parameter('config.rate').value
        self.time_tack = self.get_parameter('force_jibe.time_tack').value

        self.sailing_state = 'normal'
        self.previous_sailing_state = 'normal'
        self.timer_start = time.time()

        self.jibe_tack_now_pub = self.create_publisher(String, 'jibe_tack_now', 10)
        self.create_subscription(String, 'sailing_state', self.update_sailing_state, 10)

        self.timer = self.create_timer(1.0 / rate_hz, self.looper)

    def update_sailing_state(self, msg):
        self.sailing_state = msg.data
        if msg.data == 'normal' or self.previous_sailing_state != self.sailing_state:
            self.timer_start = time.time()
        self.previous_sailing_state = self.sailing_state

    def looper(self):
        if self.sailing_state != 'normal':
            elapsed = time.time() - self.timer_start
            if elapsed > self.time_tack:
                self.get_logger().warn('Forcing jibe/tack after %.1fs' % elapsed)
                msg = String()
                if self.sailing_state == 'switch_to_port_tack':
                    msg.data = 'jibe_now_port'
                else:
                    msg.data = 'jibe_now_stbd'
                self.jibe_tack_now_pub.publish(msg)
                self.timer_start = time.time()


def main(args=None):
    rclpy.init(args=args)
    node = ForceJibe()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
