#!/usr/bin/env python3

import time
import collections
import numpy as np
import random
import rclpy
from rclpy.node import Node
from std_msgs.msg import Float64, Float32, Int16, String, Bool

from sailing_robot.sail_table import SailTable, SailData
from sailing_robot.pid_data import PID_Data
import sailing_robot.pid_control as _PID
from sailing_robot.navigation import angle_subtract


WIND      = object()
SHEET_IN  = object()
SHEET_OUT = object()

PID_GOAL_HEADING  = object()
PID_ANGLE_TO_WIND = object()
RUDDER_FULL_LEFT  = object()
RUDDER_FULL_RIGHT = object()


class Helming(Node):
    def __init__(self):
        super().__init__('helming')

        self.declare_parameter('rudder.control.Kp', 0.5)
        self.declare_parameter('rudder.control.Ki', 0.0)
        self.declare_parameter('rudder.control.Kd', 0.0)
        self.declare_parameter('rudder.maxAngle', 40.0)
        self.declare_parameter('sailsettings.table', '{}')
        self.declare_parameter('sailsettings.sheet_out_to_jibe', False)
        self.declare_parameter('procedure.timeout', 30.0)
        self.declare_parameter('procedure.exploration_coefficient', 0.1)
        self.declare_parameter('procedure.jibe_to_turn', False)
        self.declare_parameter('config.rate', 10)

        kp = self.get_parameter('rudder.control.Kp').value
        ki = self.get_parameter('rudder.control.Ki').value
        kd = self.get_parameter('rudder.control.Kd').value
        self.max_angle = self.get_parameter('rudder.maxAngle').value
        sail_table_val = self.get_parameter('sailsettings.table').value
        if isinstance(sail_table_val, str):
            import yaml
            sail_table_dict = yaml.safe_load(sail_table_val) or {}
        else:
            sail_table_dict = sail_table_val or {}
        self.timeout = self.get_parameter('procedure.timeout').value
        self.explore_coef = self.get_parameter('procedure.exploration_coefficient').value
        jibe_to_turn = self.get_parameter('procedure.jibe_to_turn').value
        rate_hz = self.get_parameter('config.rate').value

        self.controller = _PID.PID(kp, ki, kd, self.max_angle, -self.max_angle)
        sail_table = SailTable(sail_table_dict)
        self.sail_data = SailData(sail_table)
        self.data = PID_Data()
        self.remote_control = False

        self.pub_rudder = self.create_publisher(Int16, 'rudder_control', 10)
        self.pub_sailsheet = self.create_publisher(Float32, 'sailsheet_normalized', 10)
        self.pub_dbg = self.create_publisher(String, 'dbg_helming_procedure', 10)

        self.create_subscription(Float64, 'wind_direction_apparent', self.sail_data.update_wind, 10)
        self.create_subscription(Float32, 'goal_heading', self.data.update_goal_heading, 10)
        self.create_subscription(Float32, 'heading', self.data.update_heading, 10)
        self.create_subscription(String, 'sailing_state', self.data.update_sailing_state, 10)
        self.create_subscription(Float32, 'tack_rudder', self.data.update_tack_rudder, 10)
        self.create_subscription(Bool, 'remote_control', self._update_remote_control, 10)

        if jibe_to_turn:
            procedure_list = [JibeBasic, TackBasic, TackSheetOut, TackIncreaseAngleToWind]
        else:
            procedure_list = [TackBasic, TackSheetOut, TackIncreaseAngleToWind, JibeBasic]

        self.proc = ProcedureHandle(procedure_list, self.timeout, self.explore_coef)
        self.timer = self.create_timer(1.0 / rate_hz, self.run_loop)

    def _update_remote_control(self, msg):
        self.remote_control = msg.data

    def set_sail(self, sheet_control, offset=0.0):
        if sheet_control is WIND:
            sheet_normalized = self.sail_data.calculate_sheet_setting() + offset
        elif sheet_control is SHEET_IN:
            sheet_normalized = 0.0
        elif sheet_control is SHEET_OUT:
            sheet_normalized = 1.0
        else:
            sheet_normalized = float(sheet_control)
        sheet_normalized = float(np.clip(sheet_normalized, 0, 1))
        msg = Float32()
        msg.data = sheet_normalized
        self.pub_sailsheet.publish(msg)

    def set_rudder(self, state, angle_to_wind=0):
        if state is PID_GOAL_HEADING:
            rawangle = -self.controller.update_PID(angle_subtract(self.data.heading, self.data.goal_heading))
            angle = _PID.saturation(rawangle, -self.max_angle, self.max_angle)
        elif state is PID_ANGLE_TO_WIND:
            rawangle = -self.controller.update_PID(angle_subtract(angle_to_wind, self.sail_data.wind_direction_apparent))
            angle = _PID.saturation(rawangle, -self.max_angle, self.max_angle)
        elif state is RUDDER_FULL_LEFT:
            angle = self.max_angle
        elif state is RUDDER_FULL_RIGHT:
            angle = -self.max_angle
        else:
            angle = 0.0
        msg = Int16()
        msg.data = int(angle)
        self.pub_rudder.publish(msg)

    def publish_dbg(self, text):
        msg = String()
        msg.data = text
        self.pub_dbg.publish(msg)

    def run_loop(self):
        if self.data.sailing_state == 'normal':
            if self.proc.procedure_in_progress():
                self.get_logger().warn('Procedure success %s in %.2fs' % (
                    str(self.proc.current_procedure),
                    self.proc.current_procedure.elapsed_time()))
                self.proc.mark_success(self.remote_control, self.publish_dbg)
            self.set_rudder(PID_GOAL_HEADING)
            self.set_sail(WIND)
        else:
            self.run_procedure()

    def run_procedure(self):
        if (not self.proc.procedure_in_progress()) or                 (self.data.sailing_state != self.proc.current_procedure.sailing_state):
            self.proc.first_procedure()
            self.proc.start_procedure(self.data.sailing_state)
            self.get_logger().warn('Run procedure     ' + str(self.proc.current_procedure))
            self.publish_dbg('start ' + str(self.proc.current_procedure))
        elif self.proc.current_procedure.has_failed():
            self.get_logger().warn('Procedure failed  ' + str(self.proc.current_procedure))
            self.proc.mark_failure(self.remote_control, self.publish_dbg)
            self.proc.next_procedure()
            self.proc.start_procedure(self.data.sailing_state)
            self.get_logger().warn('Run procedure     ' + str(self.proc.current_procedure))
            self.publish_dbg('start ' + str(self.proc.current_procedure))

        sail, rudder = self.proc.current_procedure.loop()
        self.set_sail(sail)
        if isinstance(rudder, tuple):
            self.set_rudder(rudder[0], angle_to_wind=rudder[1])
        else:
            self.set_rudder(rudder)


class ProcedureBase:
    def __init__(self, sailing_state, timeout):
        self.start_time = time.time()
        self.timeout = timeout
        self.sailing_state = sailing_state

    def has_failed(self):
        return self.elapsed_time() > self.timeout

    def elapsed_time(self):
        return time.time() - self.start_time

    def __str__(self):
        return self.__class__.__name__


class TackBasic(ProcedureBase):
    def loop(self):
        if self.sailing_state == 'switch_to_port_tack':
            return WIND, RUDDER_FULL_RIGHT
        else:
            return WIND, RUDDER_FULL_LEFT


class JibeBasic(ProcedureBase):
    def loop(self):
        if self.sailing_state == 'switch_to_port_tack':
            return (WIND, 0.2), RUDDER_FULL_LEFT
        else:
            return (WIND, 0.2), RUDDER_FULL_RIGHT


class TackSheetOut(ProcedureBase):
    def loop(self):
        if self.sailing_state == 'switch_to_port_tack':
            return (WIND, 0.2), RUDDER_FULL_RIGHT
        else:
            return (WIND, 0.2), RUDDER_FULL_LEFT


class TackIncreaseAngleToWind(ProcedureBase):
    def __init__(self, sailing_state, timeout):
        super().__init__(sailing_state, timeout)
        self.beating_angle = 80

    def loop(self):
        if self.elapsed_time() < 4:
            if self.sailing_state == 'switch_to_port_tack':
                return WIND, (PID_ANGLE_TO_WIND, self.beating_angle)
            else:
                return WIND, (PID_ANGLE_TO_WIND, 360 - self.beating_angle)
        else:
            if self.sailing_state == 'switch_to_port_tack':
                return WIND, RUDDER_FULL_RIGHT
            else:
                return WIND, RUDDER_FULL_LEFT


class ProcedureHandle:
    def __init__(self, procedure_list, timeout, explore_coef):
        self.timeout = timeout
        self.explore_coef = explore_coef
        self.procedure_list = [
            {'Procedure': p, 'TimeList': collections.deque(maxlen=10), 'InitPos': i}
            for i, p in enumerate(procedure_list)
        ]
        self.current_procedure_id = 0
        self.current_procedure = None

    def procedure_in_progress(self):
        return self.current_procedure is not None

    def first_procedure(self):
        self._order_list()
        self.current_procedure_id = 0

    def next_procedure(self):
        self.current_procedure_id = (self.current_procedure_id + 1) % len(self.procedure_list)

    def _order_list(self):
        def get_weight(x):
            if x['TimeList']:
                return np.mean(x['TimeList'])
            else:
                untested = sum(not p['TimeList'] for p in self.procedure_list)
                if random.random() < (self.explore_coef / untested):
                    return 0.1 * random.random()
                else:
                    return self.timeout + x['InitPos'] * 0.01 * self.timeout
        self.procedure_list = sorted(self.procedure_list, key=get_weight)

    def mark_success(self, remote_control, publish_dbg):
        if not remote_control:
            publish_dbg('success ' + str(self.current_procedure))
            self.procedure_list[self.current_procedure_id]['TimeList'].append(
                self.current_procedure.elapsed_time())
        self.current_procedure = None

    def mark_failure(self, remote_control, publish_dbg):
        if not remote_control:
            publish_dbg('fail ' + str(self.current_procedure))
            self.procedure_list[self.current_procedure_id]['TimeList'].append(1.5 * self.timeout)
        self.current_procedure = None

    def start_procedure(self, sailing_state):
        self.current_procedure = self.procedure_list[self.current_procedure_id]['Procedure'](
            sailing_state, self.timeout)


def main(args=None):
    rclpy.init(args=args)
    node = Helming()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
