#!/usr/bin/env python

import rospy
from std_msgs.msg import Float32, Int16, String

from sailing_robot.pid_data import PID_Data
import sailing_robot.pid_control as _PID

data = PID_Data()

sail = rospy.get_param('/sail')

controller = _PID.PID(sail['control']['Kp'], sail['control']['Ki'], sail['control']['Kd'], sail['maxAngle'], -sail['maxAngle'])


def node_publisher():
    """
    Publish rudder servo angle data (Int16) to Arduino node.
    Higher level tack angle was used when in TACK manoeuvre.
    PID controller was used in other conditions.
    :rtype: object
    """
    pub = rospy.Publisher('/rudder_control', Int16, queue_size=10)  # Use UInt 16 here to minimize the memory use
    rospy.init_node('rudder_servo', anonymous=True)
    rate = rospy.Rate(10)

    while not rospy.is_shutdown():
        if data.sailing_state == 'normal':
            angle = controller.update_PID(data.goal_heading-data.heading)
        else:
            angle = data.tack_rudder

        pub.publish(int(angle))

        rate.sleep()

print(data.goal_heading)

if __name__ == '__main__':
    try:
        rospy.Subscriber('/goal_heading', Float32, data.update_goal_heading)
        rospy.Subscriber('/heading', Float32, data.update_heading)
        rospy.Subscriber('/sailing_state', String, data.update_sailing_state)
        rospy.Subscriber('/tack_rudder', Float32, data.update_tack_rudder)
        node_publisher()
    except rospy.ROSInterruptException:
        pass
