#!/usr/bin/env python3
"""Read whether the servos are being remotely controlled.

Publishes: remote_control (Bool)
"""
import time
import rclpy
from rclpy.node import Node
from std_msgs.msg import Bool

try:
    import pigpio
    PIGPIO_AVAILABLE = True
except ImportError:
    PIGPIO_AVAILABLE = False


class SensorDriverMultiplexer(Node):
    def __init__(self):
        super().__init__('sensor_driver_multiplexer')

        self.declare_parameter('multiplexer.gpio', 22)
        self.declare_parameter('config.rate', 10)

        self.gpio = self.get_parameter('multiplexer.gpio').value
        rate_hz = self.get_parameter('config.rate').value

        self.last_tick = 0
        self.last_interval = 0
        self.last_pulse_time = 0.0

        self.pub = self.create_publisher(Bool, 'remote_control', 10)

        if PIGPIO_AVAILABLE:
            self.pi = pigpio.pi()
            self.pi.set_mode(self.gpio, pigpio.INPUT)
            self.pi.callback(self.gpio, pigpio.RISING_EDGE, self.tick)
            self.pi.callback(self.gpio, pigpio.FALLING_EDGE, self.tock)
        else:
            self.pi = None
            self.get_logger().warn('pigpio not available - running in simulation mode')

        self.timer = self.create_timer(1.0 / rate_hz, self.publish_remote_control)

    def tick(self, gpio, level, tick):
        self.last_tick = tick

    def tock(self, gpio, level, tick):
        self.last_interval = tick - self.last_tick
        self.last_pulse_time = time.time()

    def publish_remote_control(self):
        msg = Bool()
        if time.time() - self.last_pulse_time > 0.1:
            msg.data = False
        else:
            msg.data = self.last_interval > 1500
        self.pub.publish(msg)


def main(args=None):
    rclpy.init(args=args)
    node = SensorDriverMultiplexer()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
