#!/usr/bin/env python
"""
Node looks up correct sail setting from table
Subscribes: wind direction apparent
Sets sail actuator to correct PWM value
"""
import rospy
from std_msgs.msg import Bool
import pigpio

# GPIO 22/RPi PIN 15 as multiplexer connection
GPIO = rospy.get_param('multiplexer/gpio', default=22)

if __name__ == '__main__':
    pi = pigpio.pi();
    pi.set_mode(GPIO, pigpio.INPUT)
    try:
        pub = rospy.Publisher('remote_control', Float32, queue_size=10)
        rate = rospy.Rate(rospy.get_param("config/rate"))

        while True:
            remote_control = pi.read(GPIO)
            pub.publish(bool(remote_control))
            rate.sleep()

    except rospy.ROSInterruptException:
        pass
