#!/usr/bin/env python3
"""Read wind direction from IMU sensor."""

from __future__ import division
import math
import collections
import rclpy
from rclpy.node import Node
from std_msgs.msg import Float64

try:
    from sailing_robot.imu_utils import ImuReader
    IMU_AVAILABLE = True
except ImportError:
    IMU_AVAILABLE = False

IMU_BUS = 1
LSM = 0x1e
LGD = 0x6a


class SensorDriverWindDirection(Node):
    def __init__(self):
        super().__init__('sensor_driver_wind_direction')

        self.declare_parameter('calibration.wind_dir.XOFFSET', 0.0)
        self.declare_parameter('calibration.wind_dir.YOFFSET', 0.0)
        self.declare_parameter('calibration.wind_dir.XSCALE', 1.0)
        self.declare_parameter('calibration.wind_dir.YSCALE', 1.0)
        self.declare_parameter('calibration.wind_dir.ANGLEOFFSET', 0.0)
        self.declare_parameter('wind.sensor_average_time', 1.0)
        self.declare_parameter('config.rate', 10)

        self.xoffset = self.get_parameter('calibration.wind_dir.XOFFSET').value
        self.yoffset = self.get_parameter('calibration.wind_dir.YOFFSET').value
        self.xscale = self.get_parameter('calibration.wind_dir.XSCALE').value
        self.yscale = self.get_parameter('calibration.wind_dir.YSCALE').value
        self.angleoffset = self.get_parameter('calibration.wind_dir.ANGLEOFFSET').value

        average_time = self.get_parameter('wind.sensor_average_time').value
        sensor_rate = self.get_parameter('config.rate').value
        ave_size = int(average_time * sensor_rate)

        self.average_list = [0] * ave_size
        self.i = 0

        self.wind_pub = self.create_publisher(Float64, 'wind_direction_apparent', 10)

        if IMU_AVAILABLE:
            self.imu = ImuReader(IMU_BUS, LSM, LGD)
            self.imu.check_status()
            self.imu.configure_for_reading()
        else:
            self.imu = None
            self.get_logger().warn('Wind IMU not available - running in simulation mode')

        self.timer = self.create_timer(1.0 / sensor_rate, self.publish_wind_direction)

    def publish_wind_direction(self):
        if self.imu is None:
            return

        _, magy, magz = self.imu.read_mag_field()
        x = (magy - self.yoffset) * self.yscale
        y = (magz - self.xoffset) * self.xscale

        angle = (math.degrees(math.atan2(y, x)) + self.angleoffset) % 360

        self.average_list[self.i % len(self.average_list)] = angle
        self.i += 1

        avg_angle = sum(self.average_list) / len(self.average_list)

        msg = Float64()
        msg.data = float(avg_angle)
        self.wind_pub.publish(msg)


def main(args=None):
    rclpy.init(args=args)
    node = SensorDriverWindDirection()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
