#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from sensor_msgs.msg import Imu

try:
    import RTIMU
    import os.path
    RTIMU_AVAILABLE = True
except ImportError:
    RTIMU_AVAILABLE = False


class ImuFusionDriver(Node):
    def __init__(self):
        super().__init__('publish_IMU_message')

        self.imu_pub = self.create_publisher(Imu, 'imu/data', 10)

        if RTIMU_AVAILABLE:
            settings_file = '../launch/parameters/RTIMULib'
            self.get_logger().info('Using calibration profile RTIMULib.ini')
            s = RTIMU.Settings(settings_file)
            self.imu_device = RTIMU.RTIMU(s)
            self.imu_device.setSlerpPower(0.02)
            self.imu_device.setGyroEnable(True)
            self.imu_device.setAccelEnable(True)
            self.imu_device.setCompassEnable(True)
            if not self.imu_device.IMUInit():
                self.get_logger().error('IMU Init failed, check connection and/or access permission')
        else:
            self.imu_device = None
            self.get_logger().warn('RTIMU not available - running in simulation mode')

        self.timer = self.create_timer(1.0 / 30.0, self.publish_imu)

    def publish_imu(self):
        if self.imu_device is None:
            return
        self.imu_device.IMURead()
        data = self.imu_device.getIMUData()

        imudata = Imu()
        imudata.orientation.x = float(data['fusionQPose'][0])
        imudata.orientation.y = float(data['fusionQPose'][1])
        imudata.orientation.z = float(data['fusionQPose'][2])
        imudata.orientation.w = float(data['fusionQPose'][3])
        imudata.linear_acceleration.x = float(data['accel'][0])
        imudata.linear_acceleration.y = float(data['accel'][1])
        imudata.linear_acceleration.z = float(data['accel'][2])
        imudata.angular_velocity.x = float(data['gyro'][0])
        imudata.angular_velocity.y = float(data['gyro'][1])
        imudata.angular_velocity.z = float(data['gyro'][2])

        self.imu_pub.publish(imudata)


def main(args=None):
    rclpy.init(args=args)
    node = ImuFusionDriver()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
