#!/usr/bin/env python3

import collections
import rclpy
from rclpy.node import Node
from std_msgs.msg import Float32, Float64

from sailing_robot.navigation import angle_average


class WindDirectionAverage(Node):
    def __init__(self):
        super().__init__('sensor_processed_wind_direction')

        self.declare_parameter('config.rate', 10)
        self.declare_parameter('wind.trend_average_time', 5.0)

        sensor_rate = self.get_parameter('config.rate').value
        ave_time = self.get_parameter('wind.trend_average_time').value
        ave_size = int(ave_time * sensor_rate)

        self.heading = 0.0
        self.wind_direction_apparent = 0.0
        self.average_list = collections.deque(maxlen=ave_size)

        self.wind_direction_average_pub = self.create_publisher(
            Float32, 'wind_direction_average', 10)
        self.create_subscription(Float32, 'heading', self.update_heading, 10)
        self.create_subscription(Float64, 'wind_direction_apparent',
                                 self.update_wind_direction_apparent, 10)

        self.timer = self.create_timer(1.0 / sensor_rate, self.publish_wind_direction_average)

    def update_heading(self, msg):
        self.heading = msg.data

    def update_wind_direction_apparent(self, msg):
        self.wind_direction_apparent = msg.data

    def publish_wind_direction_average(self):
        wind_direction = (self.wind_direction_apparent + self.heading) % 360
        self.average_list.append(wind_direction)
        wind_direction_average = angle_average(list(self.average_list))
        msg = Float32()
        msg.data = float(wind_direction_average)
        self.wind_direction_average_pub.publish(msg)


def main(args=None):
    rclpy.init(args=args)
    node = WindDirectionAverage()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
