#!/usr/bin/env python
import time
import pigpio
import rospy
from std_msgs.msg import UInt16, Int16


def setup():
    pi = pigpio.pi()
    pi.set_mode(18, pigpio.OUTPUT) # GPIO 18 as sail servo pin
    pi.set_mode(33, pigpio.OUTPUT) # GPIO 33 as rudder servo pin
    
def sailservoPWM(data):
    degrees = data.data;
    pwm = 400*(1.0*degrees/630) + 1500;
    pi.set_servo_pulsewidth(18, pwm);

def rudderservoPWM(data):
    degrees = data.data;
    pwm = 1000*(1.0*degrees + 90)/180 + 1000;
    pi.set_servo_pulsewidth(33, pwm);
        

if __name__ == '__main__':
    try:
        rospy.init_node('servo_control', anonymous=True)
        rospy.Subscriber('/rudder_control', Int16, rudderservoPWM)
        rospy.Subscriber('/sail_servo', UInt16, sailservoPWM)
        rospy.spin()
    except rospy.ROSInterruptException:
        pass
    

    

