#!/usr/bin/env python3
# Simulator for the boat position based on velocity and heading

import math
import rclpy
from rclpy.node import Node
from std_msgs.msg import Float32
from sensor_msgs.msg import NavSatFix
from sailing_robot.msg import Velocity
from sailing_robot.navigation import Navigation


class PositionSimu(Node):
    def __init__(self):
        super().__init__('simulation_position')

        self.declare_parameter('simulation.heading_init', 270.0)
        self.declare_parameter('simulation.velocity.water_stream_direction', 180.0)
        self.declare_parameter('simulation.velocity.water_stream_speed', 0.0)
        self.declare_parameter('navigation.utm_zone', 30)
        self.declare_parameter('config.rate', 10)
        self.declare_parameter('wp.list', ['wp0'])
        self.declare_parameter('wp.table', '{}')

        self.heading = self.get_parameter('simulation.heading_init').value
        self.water_stream_dir = self.get_parameter('simulation.velocity.water_stream_direction').value
        self.water_stream_speed = self.get_parameter('simulation.velocity.water_stream_speed').value
        utm_zone = self.get_parameter('navigation.utm_zone').value
        self.freq = self.get_parameter('config.rate').value

        # Parse waypoint table for initial position
        wp_table_val = self.get_parameter('wp.table').value
        if isinstance(wp_table_val, str):
            import yaml
            wp_table = yaml.safe_load(wp_table_val) or {}
        else:
            wp_table = wp_table_val or {}

        wp_list_val = self.get_parameter('wp.list').value
        if wp_table and wp_list_val:
            wp0_key = wp_list_val[0] if isinstance(wp_list_val, list) else wp_list_val
            init_position = wp_table.get(wp0_key, [50.927, -1.409])
        else:
            init_position = [50.927, -1.409]

        self.nav = Navigation(utm_zone=utm_zone)
        self.utm_position = self.nav.latlon_to_utm(init_position[0], init_position[1])
        self.velocity = (0.0, 0.0)

        self.position_pub = self.create_publisher(NavSatFix, 'position', 10)
        self.create_subscription(Float32, 'heading', self.update_heading, 10)
        self.create_subscription(Velocity, 'gps_velocity', self.update_velocity, 10)

        self.timer = self.create_timer(1.0 / self.freq, self.publish_position)
        self.get_logger().info('Position simulated')

    def update_heading(self, msg):
        self.heading = msg.data

    def update_velocity(self, msg):
        self.velocity = (
            msg.speed * math.cos(math.radians(msg.heading - self.heading)),
            msg.speed * math.sin(math.radians(msg.heading - self.heading))
        )

    def publish_position(self):
        water_stream_x = -self.water_stream_speed * math.sin(math.radians(self.water_stream_dir))
        water_stream_y = -self.water_stream_speed * math.cos(math.radians(self.water_stream_dir))

        dx = (self.velocity[0] * math.sin(math.radians(self.heading)) -
              self.velocity[1] * math.cos(math.radians(self.heading)) +
              water_stream_x) / self.freq

        dy = (self.velocity[0] * math.cos(math.radians(self.heading)) +
              self.velocity[1] * math.sin(math.radians(self.heading)) +
              water_stream_y) / self.freq

        self.utm_position = (self.utm_position[0] + dx, self.utm_position[1] + dy)
        position = self.nav.utm_to_latlon(self.utm_position[0], self.utm_position[1])

        msg = NavSatFix()
        msg.latitude = float(position.lat.decimal_degree)
        msg.longitude = float(position.lon.decimal_degree)
        self.position_pub.publish(msg)


def main(args=None):
    rclpy.init(args=args)
    node = PositionSimu()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
