#!/usr/bin/env python3
# Simulator for gps_fix

from datetime import datetime
import rclpy
from rclpy.node import Node
from sensor_msgs.msg import NavSatFix
from sailing_robot.msg import gpswtime


class GpsFixSimu(Node):
    def __init__(self):
        super().__init__('simulation_gps_fix')

        self.position = None
        self.gps_fix_pub = self.create_publisher(gpswtime, 'gps_fix', 10)
        self.create_subscription(NavSatFix, 'position', self.update_position, 10)

        self.timer = self.create_timer(1.0, self.publish_gps_fix)
        self.get_logger().info('gps fix simulated')

    def update_position(self, msg):
        self.position = msg

    def publish_gps_fix(self):
        if self.position is None:
            return
        msg = gpswtime()
        msg.fix = self.position
        msg.time_h = datetime.now().hour
        msg.time_m = datetime.now().minute
        msg.time_s = datetime.now().second
        self.gps_fix_pub.publish(msg)


def main(args=None):
    rclpy.init(args=args)
    node = GpsFixSimu()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
