#!/usr/bin/python
#
# Simulator for the wind speed node


import rospy
from std_msgs.msg import Float64, Float32
import time, math


class Wind_speed_simu():
    def __init__(self):
        self.wind_speed_pub = rospy.Publisher('/wind_speed_apparent', Float64, queue_size=10)

        rospy.init_node("simulation_wind_speed", anonymous=True)

        self.rate = rospy.Rate(rospy.get_param("/config/rate"))
        self.wind_speed = rospy.get_param("/simulation/wind/speed")

        rospy.loginfo("Wind speed simulated")
        self.wind_speed_publisher()



    def wind_speed_publisher(self):

        while not rospy.is_shutdown():

            self.wind_speed_pub.publish(self.wind_speed)

            self.rate.sleep()


if __name__ == '__main__':
    try:
        Wind_speed_simu()
    except rospy.ROSInterruptException:
        pass

