#!/usr/bin/env python3
# Simulator for the boat velocity

import math
import rclpy
from rclpy.node import Node
from std_msgs.msg import Float64, Float32, String
from sailing_robot.msg import Velocity
from sailing_robot.sail_table import SailTable
import scipy.interpolate


class VelocitySimu(Node):
    def __init__(self):
        super().__init__('simulation_velocity')

        self.declare_parameter('simulation.heading_init', 270.0)
        self.declare_parameter('simulation.velocity.tacking_punishment_time', 3.0)
        self.declare_parameter('simulation.velocity.tacking_punishment_coefficient', 0.2)
        self.declare_parameter('simulation.velocity.coefficient', 0.4)
        self.declare_parameter('simulation.velocity.minimum', 0.5)
        self.declare_parameter('simulation.velocity.coef_sailsheet_error', 1.0)
        self.declare_parameter('config.rate', 10)
        self.declare_parameter('sailsettings.table', '{}')

        self.heading = self.get_parameter('simulation.heading_init').value
        self.tacking_punishment_time = self.get_parameter('simulation.velocity.tacking_punishment_time').value
        self.tacking_punishment_coef = self.get_parameter('simulation.velocity.tacking_punishment_coefficient').value
        self.velocity_coefficient = self.get_parameter('simulation.velocity.coefficient').value
        self.velocity_minimum = self.get_parameter('simulation.velocity.minimum').value
        self.coef_sailsheet_error = self.get_parameter('simulation.velocity.coef_sailsheet_error').value
        self.freq = self.get_parameter('config.rate').value

        sail_table_val = self.get_parameter('sailsettings.table').value
        if isinstance(sail_table_val, str):
            import yaml
            sail_table_dict = yaml.safe_load(sail_table_val) or {}
        else:
            sail_table_dict = sail_table_val or {}

        self.sail_table = SailTable(sail_table_dict)
        self.punishment = 1.0
        self.wind_direction = 0.0
        self.wind_speed = 0.0
        self.sailing_state = 'normal'
        self.sailsheet_normalized = 0.0

        self.velocity_pub = self.create_publisher(Velocity, 'gps_velocity', 10)
        self.create_subscription(Float32, 'heading', self.update_heading, 10)
        self.create_subscription(Float64, 'wind_direction_apparent', self.update_wind_direction, 10)
        self.create_subscription(Float64, 'wind_speed_apparent', self.update_wind_speed, 10)
        self.create_subscription(String, 'sailing_state', self.update_sailing_state, 10)
        self.create_subscription(Float32, 'sailsheet_normalized', self.update_sailsheet_normalized, 10)

        self.polardef()
        self.timer = self.create_timer(1.0 / self.freq, self.publish_velocity)
        self.get_logger().info('Velocity simulated')

    def update_heading(self, msg):
        self.heading = msg.data

    def update_wind_direction(self, msg):
        self.wind_direction = msg.data

    def update_wind_speed(self, msg):
        self.wind_speed = msg.data

    def update_sailing_state(self, msg):
        prev = self.sailing_state
        self.sailing_state = msg.data
        if self.sailing_state == 'normal':
            if prev != self.sailing_state:
                self.punishment = self.tacking_punishment_coef
        else:
            if self.punishment < 1:
                self.punishment += (1 - self.tacking_punishment_coef) / (
                    self.tacking_punishment_time * self.freq)

    def update_sailsheet_normalized(self, msg):
        self.sailsheet_normalized = msg.data

    def polardef(self):
        ang_pol = [0, 13.37, 25.95, 27.08, 30.44, 35.67, 42.03, 49.77,
                   58.30, 64.81, 71.96, 79.81, 89.71, 98.20, 112.84,
                   122.08, 131.04, 139.54, 151.12, 162.55, 175.40, 180]
        speed_pol = [0.062, 0.077, 0.157, 0.242, 0.365, 0.476, 0.598,
                     0.720, 0.812, 0.869, 0.935, 0.976, 1.000, 0.993,
                     0.959, 0.927, 0.887, 0.833, 0.772, 0.734, 0.691, 0.689]
        self.polar = scipy.interpolate.interp1d(ang_pol, speed_pol)

    def publish_velocity(self):
        wind_direction_180 = 180 - abs(self.wind_direction - 180)
        sheet_normalized_ideal = self.sail_table.interpolate_sail_setting(wind_direction_180)
        sailsheet_error_norm = abs(self.sailsheet_normalized - sheet_normalized_ideal)

        velx = (self.polar(wind_direction_180) * self.wind_speed *
                self.velocity_coefficient *
                (1 - sailsheet_error_norm * self.coef_sailsheet_error))
        if velx < self.velocity_minimum:
            velx = self.velocity_minimum

        velocity = Velocity()
        velocity.speed = float(velx * self.punishment)
        velocity.heading = float(self.heading)
        self.velocity_pub.publish(velocity)


def main(args=None):
    rclpy.init(args=args)
    node = VelocitySimu()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
