#!/usr/bin/env python3
# Simulator for the heading

import math
import rclpy
from rclpy.node import Node
from std_msgs.msg import Float32, Int16
from sailing_robot.msg import Velocity


class HeadingSimu(Node):
    def __init__(self):
        super().__init__('simulation_heading')

        self.declare_parameter('simulation.heading_init', 270.0)
        self.declare_parameter('simulation.heading.coefficient', 1.0)
        self.declare_parameter('config.rate', 10)

        self.heading = self.get_parameter('simulation.heading_init').value
        self.diff_heading_coefficient = self.get_parameter('simulation.heading.coefficient').value
        self.freq = self.get_parameter('config.rate').value

        self.rudder = 0.0
        self.speed = 0.0

        self.heading_pub = self.create_publisher(Float32, 'heading', 10)
        self.create_subscription(Int16, 'rudder_control', self.update_rudder, 10)
        self.create_subscription(Velocity, 'gps_velocity', self.update_velocity, 10)

        self.timer = self.create_timer(1.0 / self.freq, self.publish_heading)
        self.get_logger().info('Heading simulated')

    def update_rudder(self, msg):
        self.rudder = float(msg.data)

    def update_velocity(self, msg):
        self.speed = msg.speed

    def diff_heading(self):
        if self.rudder == 0:
            return 0.0
        Ay = -0.25
        r = 0.05
        By = Ay * 2
        Cx = -r * math.sin(math.radians(self.rudder))
        Cy = By - r * math.cos(math.radians(self.rudder))
        d = self.speed / self.freq
        discriminant = (Cx**4 + Cy**4 - 2*Ay*Cy**3 + Ay**2*Cy**2 +
                        2*Cx**2*Cy**2 - 4*Cx**2*d**2 - 2*Ay*Cx**2*Cy +
                        4*Ay*Cx**2*d)
        if discriminant < 0:
            return 0.0
        x = (-(-Cx**2 - Cy**2 + Ay*Cy + math.sqrt(discriminant)) / (2*Cx))
        y = d
        return -math.degrees(math.atan2(y, x)) + 90

    def publish_heading(self):
        self.heading = (self.diff_heading_coefficient * self.diff_heading() + self.heading) % 360
        msg = Float32()
        msg.data = float(self.heading)
        self.heading_pub.publish(msg)


def main(args=None):
    rclpy.init(args=args)
    node = HeadingSimu()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
