#!/usr/bin/env python3
# Node receives sailing_state from heading_control
# Outputs tack_sail and tack_rudder to override normal direction control

import rclpy
from rclpy.node import Node
from std_msgs.msg import Float32, String

from sailing_robot.tack_control import Tacking


class TackNode(Node):
    def __init__(self):
        super().__init__('publish_tack_data')

        self.sail_pub = self.create_publisher(Float32, 'tack_sail', 10)
        self.rudder_pub = self.create_publisher(Float32, 'tack_rudder', 10)
        self.tacking = Tacking()

        self.create_subscription(String, 'sailing_state', self.recv, 10)

    def recv(self, msg):
        sail, rudder = self.tacking.calculate_sail_and_rudder(msg.data)
        sail_msg = Float32()
        sail_msg.data = float(sail)
        rudder_msg = Float32()
        rudder_msg.data = float(rudder)
        self.sail_pub.publish(sail_msg)
        self.rudder_pub.publish(rudder_msg)


def main(args=None):
    rclpy.init(args=args)
    node = TackNode()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
