#!/usr/bin/env python3

import collections
import math
import numpy as np
import rclpy
from rclpy.node import Node
from scipy.signal import argrelextrema
from std_msgs.msg import Float32
from sensor_msgs.msg import Imu


class WavePeriod(Node):
    def __init__(self):
        super().__init__('wave_period_node')

        self.AccZ = collections.deque(maxlen=500)
        self.Acc_Y = 0.0
        self.Acc_Z = 0.0
        self.Acc_X = 0.0

        self.wave_period_pub = self.create_publisher(Float32, 'wave_period', 10)
        self.roll_angle_pub = self.create_publisher(Float32, 'roll_angle', 10)

        self.create_subscription(Imu, '/imu/data', self.update_acc_z, 10)
        self.timer = self.create_timer(0.1, self.period_publisher)

    def update_acc_z(self, msg):
        self.Acc_X = msg.linear_acceleration.x
        self.Acc_Y = msg.linear_acceleration.y
        self.Acc_Z = msg.linear_acceleration.z
        self.AccZ.append(self.Acc_Z)

    def period_publisher(self):
        if len(self.AccZ) < 500:
            return
        # Publish wave period and roll angle
        msg = Float32()
        msg.data = 0.0
        self.wave_period_pub.publish(msg)

        roll_msg = Float32()
        if abs(self.Acc_Z) > 0.001:
            roll_msg.data = float(math.degrees(math.atan2(self.Acc_Y, self.Acc_Z)))
        else:
            roll_msg.data = 0.0
        self.roll_angle_pub.publish(roll_msg)


def main(args=None):
    rclpy.init(args=args)
    node = WavePeriod()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
