#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from std_msgs.msg import Float32
from sensor_msgs.msg import Imu
from sailing_robot.wave_position import Wave_position


class WavePositionNode(Node):
    def __init__(self):
        super().__init__('wave_position')

        self.declare_parameter('wave_position.time_range', 10.0)
        self.declare_parameter('wave_position.refresh_time', 5.0)
        self.declare_parameter('config.rate', 10)

        time_range = self.get_parameter('wave_position.time_range').value
        refresh_time = self.get_parameter('wave_position.refresh_time').value
        frequency = self.get_parameter('config.rate').value

        self.wp = Wave_position(frequency, time_range, refresh_time)
        self.pub = self.create_publisher(Float32, 'wave_position', 10)

        self.create_subscription(Imu, '/imu/data', self.update_wp_queue, 10)
        self.timer = self.create_timer(1.0 / frequency, self.talker)

    def update_wp_queue(self, msg):
        self.wp.update(msg.linear_acceleration.z)

    def talker(self):
        result = self.wp.get_wave_position()
        if result is not None:
            msg = Float32()
            msg.data = float(result)
            self.pub.publish(msg)


def main(args=None):
    rclpy.init(args=args)
    node = WavePositionNode()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
